export default {
    SIGNUP:{
        path:'/user/signup',
        auth:false
    },
    LOGIN:{
        path:'/user/login',
        auth:false
    },
    FORGOT_PASSWORD:{
        path:'/user/forgotPassword',
        auth:false
    },
    RESET_PASSWORD:{
        path:'/user/resetPassword',
        auth:false
    },
    CREATE_HOME:{
        path:'/url/getShortUrl',
        auth:true
    },
    CREATE_URL:{
        path:'/url/createShortUrl',
        auth:true
    },
    REDIRECT_URL:{
        path:'/url/redirect',
        auth:true
    },
    DELETE_URL:{
        path:'/url/deleteUrl',
        auth:true
    },
    UPDATE_URL:{
        path:'/url/updateUrl',
        auth:true
    },
    GET_BY_ID_URL:{
        path:'/url/getUrlByShortUrl',
        auth:true
    }
}